### ISSUE TITLE
Install blocked by old version of `pip`

### ISSUE THREAD

**Issue by jneo8** [canonical/charm-duplicity#12]
The `install` hook fails due to an old version of `pip`.

When installing "fabric" via pip, the dependency "cryptography" fails with a message stating the version of pip is too old and a traceback as follows: [0]

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/lib/pip/pip-build-y4ldt5j2/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

The `install` hook succeeds when the modification for bug 1968366 is applied alongside an upgrade of pip as follows:
$ python -m pip install --upgrade pip

If possible, the charm needs to ensure the supported version of pip is available for the dependencies it intends to install during the `install` hook.

[0]: https://pastebin.canonical.com/p/f4YtDSB546/

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-04-08T18:08:52Z
 * owner: [jplettman](https://launchpad.net/~jplettman)
 * assignee: [rgildein](https://launchpad.net/~rgildein)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1968367)

**Comment by jneo8** [comment]
(by [vultaire](https://launchpad.net/~vultaire))
If this is a charmcraft-built charm, this is easy to fix.  I've done this for a few charms already.

See here: https://discourse.charmhub.io/t/install-or-update-python-packages-before-packing-a-charm/5158

**Comment by jneo8** [comment]
(by [raychan96](https://launchpad.net/~raychan96))
For which release are you seeing this problem? I saw bionic is having similar problem: missing rustc.

**Comment by jneo8** [comment]
(by [valexby](https://launchpad.net/~valexby))
Hi Ray,

The series are Bionic, duplicity is of version 0.7.17-0ubuntu1.1 and the charm is revision 12.

Hope that helps.

**Comment by jneo8** [comment]
(by [rgildein](https://launchpad.net/~rgildein))
Hi Paul (@vultaire) we could not use `charm-python-packages`, since this is reactive charm
and we are using reactive plugin.

However we potentially could use `build-packages` and define `fabric` (`cryptography`) in
wheelhouse.txt instead of installing in with layers. However I could not make it work, so for
now I proposed only add `pkg-config` and disabling `include_system_packages`.
